import { AGENT_TOOL_RESULT_MAX_CHARS } from './context-budget';

/** Browser counters intentionally contain no page text or tool arguments. */
export type BrowserExecutionMetrics = {
  browserToolCallCount: number;
  browserToolSuccessCount: number;
  browserToolFailureCount: number;
  browserToolDurationMs: number;
  browserToolResultChars: number;
  browserToolContextChars: number;
  browserSnapshotCount: number;
  browserSnapshotChars: number;
  browserSnapshotTruncationCount: number;
  browserSnapshotDuplicateCount: number;
  browserSnapshotStateChanges: number;
  browserSnapshotUnchangedCount: number;
};

const EMPTY_METRICS: BrowserExecutionMetrics = {
  browserToolCallCount: 0,
  browserToolSuccessCount: 0,
  browserToolFailureCount: 0,
  browserToolDurationMs: 0,
  browserToolResultChars: 0,
  browserToolContextChars: 0,
  browserSnapshotCount: 0,
  browserSnapshotChars: 0,
  browserSnapshotTruncationCount: 0,
  browserSnapshotDuplicateCount: 0,
  browserSnapshotStateChanges: 0,
  browserSnapshotUnchangedCount: 0,
};

function nonNegativeFinite(value: unknown) {
  const number = Number(value);
  return Number.isFinite(number) && number >= 0 ? number : 0;
}

function snapshotFingerprint(value: string) {
  // Refs are regenerated by some browser backends even when the rendered state is unchanged.
  const stable = value
    .replace(/\[ref=[^\]]+\]/g, '')
    .replace(/\[(?:truncated|截断|已截断)\]/ig, '')
    .replace(/\s+/g, ' ')
    .trim();
  let hash = 2166136261;
  for (let index = 0; index < stable.length; index += 1) {
    hash ^= stable.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16);
}

function appearsTruncated(value: string) {
  return value.length >= AGENT_TOOL_RESULT_MAX_CHARS
    || /(?:truncated|截断|已截断|内容过长)/i.test(value);
}

export function createBrowserMetricsCollector() {
  const metrics: BrowserExecutionMetrics = { ...EMPTY_METRICS };
  let previousSnapshot: string | null = null;

  return {
    record(toolName: unknown, ok: unknown, result: unknown, durationMs: unknown): string {
      const name = String(toolName || '');
      const text = String(result ?? '');
      const succeeded = ok === true;
      metrics.browserToolCallCount += 1;
      metrics.browserToolSuccessCount += succeeded ? 1 : 0;
      metrics.browserToolFailureCount += succeeded ? 0 : 1;
      metrics.browserToolDurationMs += nonNegativeFinite(durationMs);
      metrics.browserToolResultChars += text.length;

      if (name !== 'browser_snapshot' || !succeeded) {
        metrics.browserToolContextChars += text.length;
        return text;
      }
      let contextText = text;
      metrics.browserSnapshotCount += 1;
      metrics.browserSnapshotChars += text.length;
      metrics.browserSnapshotTruncationCount += appearsTruncated(text) ? 1 : 0;
      const fingerprint = snapshotFingerprint(text);
      if (previousSnapshot !== null) {
        if (previousSnapshot === fingerprint) {
          metrics.browserSnapshotUnchangedCount += 1;
          const refs = text.split('\n').filter((line) => /\[ref=[^\]]+\]/.test(line)).join('\n').slice(0, 4_000);
          const compactText = `### Snapshot\n[页面状态与上一份快照相同；以下保留当前可操作元素引用]\n${refs || '（没有可操作元素引用）'}`;
          if (compactText.length < text.length) contextText = compactText;
        }
        else metrics.browserSnapshotStateChanges += 1;
      }
      metrics.browserSnapshotDuplicateCount += contextText !== text ? 1 : 0;
      previousSnapshot = fingerprint;
      metrics.browserToolContextChars += contextText.length;
      return contextText;
    },
    hasActivity() {
      return metrics.browserToolCallCount > 0;
    },
    snapshot() {
      return { ...metrics };
    },
  };
}
